device: "cuda"
save_dir: "saves/"
task: quadrotor
seed: 1

algo: gpmpc_acados_TRP

algo_config:
  horizon: 25
  q_mpc: [8, 0.1, 8, 0.1, 8, 0.1, 0.5, 0.5, 0.001,0.001]
  r_mpc: [3, 3, 3]
  optimization_iterations:
    - 500
    - 500
    - 500
  learning_rate:
    - 0.001
    - 0.001
    - 0.001
  prior_info:
    prior_prop:
      M: 0.033 # Must be capitcal M 
      a: 12.1432
      b: 1.8118
      c: -72.08
      d: -7.5755
      e: 39.8653
      f: -72.08
      h: -7.5755
      l: 39.8653
  initial_rollout_std: 0.0
  prob: 0.95
  device: "cuda"
  sparse_gp: true
  n_ind_points: 40
  num_samples: 20
  output_dir: ./gpmpc_acados_TRP/results

run:
  num_epochs: 3

train:
  test_data_ratio: 0.2


# Try not to change this information
task_config:
  info_in_reset: True
  ctrl_freq: 60
  pyb_freq: 60
  physics: dyn_si_3d_10
  quad_type: 8

  init_state:
    init_x: 0
    init_x_dot: 0
    init_z: 1.0
    init_z_dot: 0
    init_theta: 0
    init_theta_dot: 0
  randomized_init: True
  randomized_inertial_prop: False

  init_state_randomization_info:
    init_x:
      distrib: 'normal'
      scale: 0.0011629923113331312
    init_x_dot:
      distrib: 'normal'
      scale: 0.003635597781389117
    init_y:
      distrib: 'normal'
      scale: 0.001670549279531124
    init_y_dot:
      distrib: 'normal'
      scale: 0.004965500657569368
    init_z:
      distrib: 'normal'
      scale: 0.0024990695232428458
    init_z_dot:
      distrib: 'normal'
      scale: 0.010193088084183025
    init_phi:
      distrib: 'normal'
      scale: 0.0026984744060397532
    init_theta:
      distrib: 'normal'
      scale: 0.0024088251667187467
    init_p:
      distrib: 'normal'
      scale: 0.03452115832640752
    init_q:
      distrib: 'normal'
      scale: 0.02387283406599296

  task: traj_tracking
  task_info:
    trajectory_type: figure8
    num_cycles: 2
    trajectory_plane: 'xy'
    trajectory_position_offset: [0, 0.]
    trajectory_scale: 1.0

  episode_len_sec: 11
  cost: quadratic

  constraints:
    - constraint_form: default_constraint
      constrained_variable: state
    - constraint_form: default_constraint
      constrained_variable: input

  done_on_out_of_bound: True
  done_on_violation: False
  disturbances:
    observation:
      - disturbance_func: white_noise
        std: [5.6e-05, 1.5e-02, 
              5.6e-05, 1.5e-02,
              2.9e-05, 8.0e-03,
              1.3e-03, 1.3e-03, 
              3.5e-03, 3.5e-03]
