save_dir: "saves/"
task: quadrotor
seed: 1

gpmpc:
  horizon: 25
  q_mpc: [8, 0.1, 8, 0.1, 8, 0.1, 0.5, 0.5, 0.5, 0.001, 0.001, 0.001]
  r_mpc: [3, 3, 3, 0.1]
  prior_params:
    a: 12.1432
    b: 1.8118
    c: -72.08
    d: -7.5755
    e: 39.8653
    f: -72.08
    h: -7.5755
    l: 39.8653
  prob: 0.95
  device: "cpu"
  sparse_gp: true
  max_gp_samples: 40

run:
  num_epochs: 3

train:
  eval_size: 0.2
  iterations: 500
  lr: 0.001
  samples_per_epoch: 15
